### ISSUE TITLE
Bluetooth connection error

### ISSUE THREAD

**Issue by nicofrancis** [ImACoderImACoderImACoder/onyx#11]
I get this error when trying to connect to bluetooth. using newest version of chrome on macOS monterrey. Haven't been able to make it past this error. 

<img width="451" alt="Screen Shot 2022-07-04 at 9 35 10 PM" src="https://user-images.githubusercontent.com/42902590/177244521-edce43a7-f7b7-45ad-acf7-1124cf4fc092.png">

**Comment by ImACoderImACoderImACoder** [comment]
That is so cool that GitHub knows I reference the issue in my commit!

@nicofrancis Thank you for bringing this to my attention

 It is now fixed!
